name: 'Python on Windows'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - run: |
          Get-Location | Foreach-Object { $_.Path }
          Get-ChildItem -Path .
          $env:PATH -split ';'
          py --version  # >= 3.12.x expected
          py -m pip -V

      - run: |
          py -m venv .win64-venv
          .\.win64-venv\Scripts\activate
          py -m pip install conan
          deactivate

      - run: |
          .\.win64-venv\Scripts\activate
          conan profile detect --force --name default
          deactivate

      - run: |
           Get-Location 

      - run: |
          .win64-venv\Scripts\activate
          py -m pip install multipledispatch signature_dispatch
          py script.py
          deactivate

